name: Daily Coupon Change Check & Notify

on:
  schedule:
    - cron: '0 9 * * *'  # Runs daily at 09:00 UTC
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  notify:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4

      - name: Run script
        id: run_script
        run: |
          python scrapper.py
        continue-on-error: true

      - name: Compare current coupon data with previous
        id: check_changes
        run: |
          echo "Previous code: ${{ vars.PREVIOUS_COUPON_CODE }}"
          echo "Previous description: ${{ vars.PREVIOUS_COUPON_DESCRIPTION }}"
          if [[ "${{ env.COUPON_CODE }}" != "${{ vars.PREVIOUS_COUPON_CODE }}" || "${{ env.COUPON_DESCRIPTION }}" != "${{ vars.PREVIOUS_COUPON_DESCRIPTION }}" ]]; then
            echo "Changes detected"
            echo "CHANGED=true" >> $GITHUB_ENV
          else
            echo "No changes detected"
            echo "CHANGED=false" >> $GITHUB_ENV
          fi

      - name: Send email notification if changes detected
        if: env.CHANGED == 'true'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp-mail.outlook.com
          server_port: 25
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          to: ${{ secrets.EMAIL_USERNAME_TO }}
          from: ${{ secrets.EMAIL_USERNAME }}
          subject: CottonCarrier Coupon Daily Update - Set Up By STEVEN BRADLEY
          body: |
            This is your daily email notification.
            Content from the Python script:
            Code: ${{ env.COUPON_CODE }}
            Description: ${{ env.COUPON_DESCRIPTION }}
        continue-on-error: true

      - name: Send Slack notification if changes detected
        if: env.CHANGED == 'true'
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text":"Mise à jour des coupons CottonCarrier\nCode: ${{ env.COUPON_CODE }}\nDescription: ${{ env.COUPON_DESCRIPTION }}"}' \
          ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Check API access
        run: |
          gh api /repos/${{ github.repository }}/actions/variables
        env:
          GH_TOKEN: ${{ secrets.YOUR_PAT_SECRET }}

      - name: Debug token
        run: |
          echo "GH_TOKEN exists: ${YOUR_PAT_SECRET:+yes}"

      - name: Update GitHub Variables with current coupon data
        if: env.CHANGED == 'true'
        run: |
          gh api --method PATCH \
            -H "Accept: application/vnd.github+json" \
            /repos/${{ github.repository }}/actions/variables/PREVIOUS_COUPON_CODE \
            -f name=PREVIOUS_COUPON_CODE \
            -f value="${{ env.COUPON_CODE }}"
          gh api --method PATCH \
            -H "Accept: application/vnd.github+json" \
            /repos/${{ github.repository }}/actions/variables/PREVIOUS_COUPON_DESCRIPTION \
            -f name=PREVIOUS_COUPON_DESCRIPTION \
            -f value="${{ env.COUPON_DESCRIPTION }}"
        env:
          GH_TOKEN: ${{ secrets.YOUR_PAT_SECRET }}